version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: nutriapp
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    command: pnpm --filter=@appplaceholder/api dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_URL: "postgresql://postgres:postgrespw@db:5432/nutriapp?schema=public"
    ports:
      - "3333:3333"
    depends_on:
      - db

  web:
    build: false
    command: pnpm --filter=@appplaceholder/web dev -p 3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: "http://api:3333/api"
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db-data:
