services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: nutriapp
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:postgrespw@db:5432/nutriapp?schema=public"
      NODE_ENV: production
    ports:
      - "3333:3333"
    depends_on:
      - db

volumes:
  db-data:
