name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Setup pnpm
        run: corepack enable && corepack prepare pnpm@8.0.0 --activate
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Generate Prisma client
        run: pnpm -w -r run prisma:generate
      - name: Lint (root)
        run: pnpm -w -r lint || true
      - name: Typecheck
        run: pnpm -w -r run tsc --noEmit
      - name: Run tests
        run: pnpm -w -r test
      - name: Build apps
        run: pnpm -w -r build
